name: VisualWand
version: ${project.version}
main: cafe.minigames.visualwand.VisualWand
api-version: '1.21'
author: Nariaris
description: In-Game Display Entity Editor with Gizmo Transformations

commands:
  visualwand:
    description: Main VisualWand command
    aliases: [vw, wand]
    permission: visualwand.use
  vwgive:
    description: Give the Architect's Wand
    permission: visualwand.give

permissions:
  visualwand.use:
    description: Allows using VisualWand
    default: op
  visualwand.give:
    description: Allows giving the wand
    default: op
  visualwand.admin:
    description: Full access to VisualWand
    default: op
    children:
      visualwand.use: true
      visualwand.give: true
